---

wordpress:
  image: wordpress
  links:
    - wordpress_db:mysql
  ports:
    - 8080:80
#  volumes:
#    - ~/Docker_Stuff/wordpress/wp_html:/var/www/html


wordpress_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: password
  ports:
    - 3306:3306


phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: password

