---

- name: Pull MariaDB image
  command: "/usr/bin/docker pull mariadb"

- name: Create MariaDB for Wordpress 
  docker:
    name: wordpress_db
    image: mariadb
    pull: missing
    env:
      #MYSQL_ROOT_PASSWORD: password
       MYSQL_ROOT_PASSWORD={{ mysql_root_password }}
    ports:
     - "8686:3306"
    state: started
    

- name: Pull Wordpress image
  command: "/usr/bin/docker pull wordpress"



- name: Create Worpress Docker container
  docker:
    name: wordpress
    image: wordpress
    pull: missing
    links:
     - wordpress_db:mysql
    ports:
     - "8080:80"
    state: started


- name: Pull PHPMyAdmin image
  command: "/usr/bin/docker pull corbinu/docker-phpmyadmin"


- name: Create Docker container for PHP MyAdmin
  docker:
    name: wordpress_phpmyadmin
    image: corbinu/docker-phpmyadmin
    pull: missing
    links: 
      - wordpress_db:mysql
    ports:
      - 8181:80
    env:
        #MYSQL_USERNAME: root,
        WORDPRESS_DB_PASSWORD={{ wordpress_mysql_root_password }}
    state: started



